# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-13 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgid', models.CharField(max_length=16)),
                ('imgname', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'mv_loginimg',
            },
        ),
    ]
