# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-16 13:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_movies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginimg',
            name='imgid',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='movieid',
        ),
    ]
