# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-16 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20181116_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='content',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='movies',
            name='downloadlink',
            field=models.CharField(max_length=500),
        ),
    ]
