# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-18 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20181116_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginimg',
            name='imgname',
            field=models.CharField(max_length=200),
        ),
    ]
