# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-19 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20181118_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=64, unique=True)),
                ('sex', models.BooleanField(default=True)),
                ('age', models.IntegerField(default=18, max_length=3)),
                ('icon', models.ImageField(upload_to='upload/')),
            ],
            options={
                'db_table': 'mv_user',
            },
        ),
    ]
