# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-19 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20181119_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=models.ImageField(default='default.jpg', upload_to='upload/'),
        ),
    ]
